terminal_width = 80
terminal_height = 24

[[windows]]
name = "main"
widget_type = "text"
streams = ["main"]
row = 1
col = 9
rows = 22
cols = 71
buffer_size = 10000
show_border = true
transparent_background = true
locked = false
numbers_only = false

[[windows]]
name = "command_input"
widget_type = "command_input"
streams = []
row = 23
col = 9
rows = 1
cols = 71
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
content_align = "center"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 3
min_cols = 20
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "compass"
widget_type = "compass"
streams = []
row = 21
col = 1
rows = 3
cols = 7
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Exits"
content_align = "center"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 3
max_rows = 3
min_cols = 7
max_cols = 7
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "injuries"
widget_type = "injury_doll"
streams = []
row = 13
col = 0
rows = 6
cols = 8
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Injuries"
content_align = "center"
background_color = "#000000"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
min_rows = 6
max_rows = 6
min_cols = 8
max_cols = 8
numbers_only = false
injury_default_color = "#333333"
injury1_color = "#aa5500"
injury2_color = "#ff8800"
injury3_color = "#ff0000"
scar1_color = "#999999"
scar2_color = "#777777"
scar3_color = "#555555"

[[windows]]
name = "casttime"
widget_type = "countdown"
streams = []
row = 10
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Cast"
content_align = "center"
background_color = "#000000"
bar_color = "#0000ff"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "stuntime"
widget_type = "countdown"
streams = []
row = 9
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Stun"
content_align = "center"
background_color = "#000000"
bar_color = "#ffff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "roundtime"
widget_type = "countdown"
streams = []
row = 11
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "RT"
content_align = "center"
background_color = "#000000"
bar_color = "#ff0000"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "spellhand"
widget_type = "spellhand"
streams = []
row = 0
col = 53
rows = 1
cols = 22
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
border_sides = [
    "left",
    "right",
]
title = "Spell"
content_align = "center"
background_color = "#000000"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
hand_icon = "S:"
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "lefthand"
widget_type = "lefthand"
streams = []
row = 0
col = 9
rows = 1
cols = 22
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
border_sides = ["left"]
title = "Left Hand"
content_align = "center"
background_color = "#000000"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
hand_icon = "L:"
text_color = "#909090"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "righthand"
widget_type = "righthand"
streams = []
row = 0
col = 31
rows = 1
cols = 22
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
border_sides = ["left"]
title = "Right Hand"
content_align = "center"
background_color = "#000000"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
hand_icon = "R:"
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "health"
widget_type = "progress"
streams = []
row = 7
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Health"
content_align = "center"
background_color = "#000000"
bar_color = "#6e0202"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "mana"
widget_type = "progress"
streams = []
row = 6
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Mana"
content_align = "center"
background_color = "#000000"
bar_color = "#08086d"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "stamina"
widget_type = "progress"
streams = []
row = 5
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Stamina"
content_align = "center"
background_color = "#000000"
bar_color = "#bd7b00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "spirit"
widget_type = "progress"
streams = []
row = 4
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Spirit"
content_align = "center"
background_color = "#000000"
bar_color = "#6e727c"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "status_dashboard"
widget_type = "dashboard"
streams = []
row = 19
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Status"
content_align = "center"
background_color = "#000000"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_spacing = 1
dashboard_hide_inactive = true
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows.dashboard_indicators]]
id = "poisoned"
icon = ""
colors = [
    "#000000",
    "#00ff00",
]

[[windows.dashboard_indicators]]
id = "diseased"
icon = ""
colors = [
    "#000000",
    "#8b4513",
]

[[windows.dashboard_indicators]]
id = "bleeding"
icon = ""
colors = [
    "#000000",
    "#ff0000",
]

[[windows.dashboard_indicators]]
id = "stunned"
icon = ""
colors = [
    "#000000",
    "#ffff00",
]

[[windows.dashboard_indicators]]
id = "webbed"
icon = "󰯊"
colors = [
    "#000000",
    "#cccccc",
]

[[windows]]
name = "encumlevel"
widget_type = "progress"
streams = []
row = 1
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Encumbrance"
content_align = "center"
background_color = "#000000"
bar_color = "#006400"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "pbarStance"
widget_type = "progress"
streams = []
row = 2
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Stance"
content_align = "center"
background_color = "#000000"
bar_color = "#000080"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "mindState"
widget_type = "progress"
streams = []
row = 0
col = 0
rows = 1
cols = 9
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Mind"
content_align = "center"
background_color = "#000000"
bar_color = "#008b8b"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 9
max_cols = 9
numbers_only = false
effect_default_color = "#ffffff"
